config/routes.rb
Rails.application.routes.draw do
  get 'calendar/show'
  resources :reminder_lists
  root 'reminder_lists#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resource :calendar, only: [:show], controller: :calendar
  root to: "calendar#show"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/reminder_list.rb
class ReminderList < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/calendar_controller.rb
class CalendarController < ApplicationController
  def show
      @date = params[:date] ? Date.parse(params[:date]) : Date.today
  end
end

app/controllers/reminder_lists_controller.rb
class ReminderListsController < ApplicationController
  before_action :set_reminder_list, only: %i[ show edit update destroy ]

  # GET /reminder_lists or /reminder_lists.json
  def index
    @reminder_lists = ReminderList.all
  end

  # GET /reminder_lists/1 or /reminder_lists/1.json
  def show
  end

  # GET /reminder_lists/new
  def new
    @reminder_list = ReminderList.new
  end

  # GET /reminder_lists/1/edit
  def edit
  end

  # POST /reminder_lists or /reminder_lists.json
  def create
    @reminder_list = ReminderList.new(reminder_list_params)

    respond_to do |format|
      if @reminder_list.save
        format.html { redirect_to  reminder_lists_url, notice: "Reminder list was successfully created." }
        format.json { render :show, status: :created, location: @reminder_list }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @reminder_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reminder_lists/1 or /reminder_lists/1.json
  def update
    respond_to do |format|
      if @reminder_list.update(reminder_list_params)
        format.html { redirect_to reminder_lists_url, notice: "Reminder list was successfully updated." }
        format.json { render :show, status: :ok, location: @reminder_list }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @reminder_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reminder_lists/1 or /reminder_lists/1.json
  def destroy
    @reminder_list.destroy

    respond_to do |format|
      format.html { redirect_to reminder_lists_url, notice: "Reminder list was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reminder_list
      @reminder_list = ReminderList.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def reminder_list_params
      params.require(:reminder_list).permit(:id, :description, :date, :isDone, :isOverDue)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/calendar_helper.rb
module CalendarHelper
 def calendar(date = Date.today, &block)
    Calendar.new(self, date, block).table
  end

end

app/helpers/reminder_lists_helper.rb
module ReminderListsHelper
end

app/views/calendar/show.html.erb
<div class="calendar-container bg-dark text-white">
  <div class="calendar-header">
    <div class="h1">
      <%= link_to calendar_path(date: @date - 1.month), class: "btn btn-default" do %>
        <i class="bi bi-arrow-left-square-fill"></i>
      <% end %>
      <%= "#{@date.strftime("%B")} #{@date.year}" %>
      <%= link_to calendar_path(date: @date + 1.month), class: "btn btn-default" do %>
        <i class="bi bi-arrow-right-square-fill"></i>
      <% end %>
    </div>
  </div>
  <div class="calendar">
    <%= calendar @date do |date| %>
      <%= date.day %>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Reminder_App</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= favicon_link_tag 'favicon.png' %>
  </head>

  <body>

  <%= render "reminder_lists/sidebar" %>

  </body>
</html>

app/views/reminder_lists/_form.html.erb
<%= form_with(model: reminder_list, local: true) do |form| %>
  <% if reminder_list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(reminder_list.errors.count, "error") %> prohibited this reminder_list from being saved:</h2>

      <ul>
      <% reminder_list.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :id %>
    <%= form.number_field :id %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="field">
    <%= form.label :date %>
    <%= form.datetime_select :date %>
  </div>

  <div class="field">
    <%= form.label :isDone %>
    <%= form.check_box :isDone %>
  </div>

  <div class="field">
    <%= form.label :isOverDue %>
    <%= form.check_box :isOverDue %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/reminder_lists/_navbar.html.erb
<nav class="navbar navbar-light bg-dark" style="margin-left: 10px; opacity: 0.9; border-radius: 5px;" >
  <div class="container-fluid">
    <a class="navbar-brand align-items-center "></a>
    <form class="d-flex">
      <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success" type="submit">Search</button>
    </form>
  </div>
</nav>

app/views/reminder_lists/_sidebar.html.erb
<div class="row h-100">
    <div class="col-auto col-sm pt-4 bg-dark" style="opacity: 0.9; border-radius: 5px;">
        <div class="d-flex flex-column align-items-center align-items-sm-start px-2 pt-2 text-white"
            style="height: 93vh">
            <i class="d-flex align-items-center pb-3 mb-md-0 me-md-auto text-white text-decoration-none">
                <span class="fs-5 d-none d-sm-inline">Menu</span>
            </i>
            <ul class="nav nav-pills flex-column mb-sm-auto mb-0 align-items-center align-items-sm-start" id="menu">
                <li class="nav-item">
                    <a href="#" class="nav-link align-middle px-0">
                        <i class="fs-4 bi-house"></i> <span class="ms-1 d-none d-sm-inline">Home</span>
                    </a>
                </li>
                <li>
                    <a href="calendar" class="nav-link px-0 align-middle">
                        <i class="fs-4 bi-calendar2-month"></i> <span class="ms-1 d-none d-sm-inline">Calendar</span>
                    </a>
                </li>
                <li>
                    <a href="/" class="nav-link px-0 align-middle">
                        <i class="fs-4 bi-card-list"></i> <span class="ms-1 d-none d-sm-inline">Event List</span> </a>
                </li>
                <li>
                    <a href="#" class="nav-link px-0 align-middle">
                        <i class="fs-4 bi-people"></i> <span class="ms-1 d-none d-sm-inline">Customers</span> </a>
                </li>
            </ul>
            <hr>
            <div class="dropdown pb-4">
                <a href="#" class="d-flex align-items-center text-white text-decoration-none dropdown-toggle bi-people"
                    id="dropdownUser1" data-bs-toggle="dropdown" aria-expanded="false">
                    <!-- <img src="https://gist.github.com/" alt="hugenerd" width="30" height="30" class="rounded-circle"> -->
                    <span class="d-none d-sm-inline mx-1">My Profile</span>
                </a>
                <ul class="dropdown-menu dropdown-menu-dark text-small shadow" aria-labelledby="dropdownUser1">
                    <li><a class="dropdown-item" href="#">Settings</a></li>
                    <li>
                        <hr class="dropdown-divider">
                    </li>
                    <li><a class="dropdown-item" href="#">Sign out</a></li>
                </ul>
            </div>
        </div>
    </div>
    <div class="col-10" style="padding: 0;">
        <%= render "reminder_lists/navbar" %>
            <div style="margin-left:12px;">
                <%= yield %>
            </div>
    </div>
</div>

<%# <li>
    <a href="#submenu1" data-bs-toggle="collapse" class="nav-link px-0 align-middle">
        <i class="fs-4 bi-speedometer2"></i> <span class="ms-1 d-none d-sm-inline">Calendar</span> </a>
    <ul class="collapse show nav flex-column ms-1" id="submenu1" data-bs-parent="#menu">
        <li class="w-100">
            <a href="calendar" class="nav-link px-0"> <span class="d-none d-sm-inline">Calendar</span> 1
            </a>
        </li>
        <li>
            <a href="/" class="nav-link px-0"> <span class="d-none d-sm-inline">List</span> 2 </a>
        </li>
    </ul>
    </li>
    <li>
        <a href="#" class="nav-link px-0 align-middle">
            <i class="fs-4 bi-table"></i> <span class="ms-1 d-none d-sm-inline">Orders</span></a>
    </li>
    <li>
        <a href="#submenu2" data-bs-toggle="collapse" class="nav-link px-0 align-middle ">
            <i class="fs-4 bi-bootstrap"></i> <span class="ms-1 d-none d-sm-inline">Bootstrap</span></a>
        <ul class="collapse nav flex-column ms-1" id="submenu2" data-bs-parent="#menu">
            <li class="w-100">
                <a href="#" class="nav-link px-0> <span class=" d-none d-sm-inline">Item</span>
                    1Test</a>
            </li>
            <li>
                <a href="#" class="nav-link px-0"> <span class="d-none d-sm-inline">Item</span> 2</a>
            </li>
        </ul>
    </li>
    <li>
        <a href="#submenu3" data-bs-toggle="collapse" class="nav-link px-0 align-middle">
            <i class="fs-4 bi-grid"></i> <span class="ms-1 d-none d-sm-inline">Products</span> </a>
        <ul class="collapse nav flex-column ms-1" id="submenu3" data-bs-parent="#menu">
            <li class="w-100">
                <a href="#" class="nav-link px-0"> <span class="d-none d-sm-inline">Product</span> 1</a>
            </li>
            <li>
                <a href="#" class="nav-link px-0"> <span class="d-none d-sm-inline">Product</span> 2</a>
            </li>
            <li>
                <a href="#" class="nav-link px-0"> <span class="d-none d-sm-inline">Product</span> 3</a>
            </li>
            <li>
                <a href="#" class="nav-link px-0"> <span class="d-none d-sm-inline">Product</span> 4</a>
            </li>
        </ul>
    </li> %>

app/views/reminder_lists/edit.html.erb
<h1>Editing Reminder List</h1>

<%= render 'form', reminder_list: @reminder_list %>

<%= link_to 'Show', @reminder_list %> |
<%= link_to 'Back', reminder_lists_path %>

app/views/reminder_lists/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Reminder Lists</h1>

<table>
  <thead>
    <tr>
      <th>Id</th>
      <th>Description</th>
      <th>Date</th>
      <th>Isdone</th>
      <th>Isoverdue</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reminder_lists.each do |reminder_list| %>
      <tr>
        <td><%= reminder_list.id %></td>
        <td><%= reminder_list.description %></td>
        <td><%= reminder_list.date %></td>
        <td><%= reminder_list.isDone %></td>
        <td><%= reminder_list.isOverDue %></td>
        <td><%= link_to 'Show', reminder_list %></td>
        <td><%= link_to 'Edit', edit_reminder_list_path(reminder_list) %></td>
        <td><%= link_to 'Destroy', reminder_list, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Reminder List', new_reminder_list_path %>

app/views/reminder_lists/new.html.erb
<h1>New Reminder List</h1>

<%= render 'form', reminder_list: @reminder_list %>

<%= link_to 'Back', reminder_lists_path %>

app/views/reminder_lists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Id:</strong>
  <%= @reminder_list.id %>
</p>

<p>
  <strong>Description:</strong>
  <%= @reminder_list.description %>
</p>

<p>
  <strong>Date:</strong>
  <%= @reminder_list.date %>
</p>

<p>
  <strong>Isdone:</strong>
  <%= @reminder_list.isDone %>
</p>

<p>
  <strong>Isoverdue:</strong>
  <%= @reminder_list.isOverDue %>
</p>

<%= link_to 'Edit', edit_reminder_list_path(@reminder_list) %> |
<%= link_to 'Back', reminder_lists_path %>